### ISSUE TITLE
Please add BankID

### ISSUE THREAD

**Issue by hstokset** [Nitrokey/dongleauth#201]
"BankID Norge" is the secure login solution used by all the banks in Norway. Please add a "tell them to support U2F" message.

They offer a number of other second factors ranging from cards with one time codes on them to hardware one time code generators to one time passphrases sent to to a cellular phone. I would love if enough people encourage them to add Yubikey/U2F support as well.

Webpage: https://www.bankid.no/privat/
U2F support: No
OTP support: Yes
Twitter: https://twitter.com/bankidnorge
Facebook: https://www.facebook.com/BankIDNorge/

**Comment by alex-nitrokey** [comment]
Dongleauth is set up in the way that only if no solution is possible there will appear a "Tell them..." button. As they support otp, the message would not appear. Nevertheless, a PR to include the site would get merged, to add them to the dongleauth list.

**Comment by 103058167** [comment]
@hstokset I could not find any recent updates in BankID's documentation suggesting the use of U2F. However, there was mention of implementing secure start through the use of QR codes, more information in the last link below. Nevertheless, dongleauth positions to look at organizations who use U2F rather than not.

If I am mistaken, please link documentation that show otherwise.

https://www.bankid.com/en/utvecklare/guider/praxis
https://www.bankid.com/assets/bankid/rp/BankID-Relying-Party-Guidelines-v3.7.pdf
https://www.bankid.com/en/utvecklare/guider/teknisk-integrationsguide

https://www.bankid.com/en/foretag/stark-koppling
